
services:
  backend:
    build:
        context: /home/root/BE
        dockerfile: Dockerfile
    container_name: backend-service
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://khoihmse171467:khoi1610@swd.tftrh.mongodb.net/Swd?retryWrites=true&w=majority
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-service
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
